# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none
# relative_permalinks: true
excerpt_separator: "<!-- more -->" # Adds read more feature


# Setup
title:            Something
tagline:          
description:      'I Learn.'
url:              http://ioio007.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ioio007/ioio007.github.io

# Gems
  gems:           [jekyll-paginate]
